# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 19:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inveratask',
            name='userTask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 43, 47, 292317)),
        ),
    ]
