# Generated by Django 2.2.17 on 2021-01-13 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210112_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 2, 0, 0, 541625, tzinfo=utc), verbose_name='Creado'),
        ),
    ]
