# Generated by Django 2.2.17 on 2021-01-13 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210112_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 1, 12, 23, 31, 36, 880062), verbose_name='Creado'),
        ),
    ]
