# Generated by Django 2.2.17 on 2021-01-13 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210112_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 23, 53, 42, 397104), verbose_name='Creado'),
        ),
    ]
