# Generated by Django 2.2.17 on 2021-01-13 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20210113_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 1, 13, 15, 58, 46, 180951), verbose_name='Creado'),
        ),
    ]
