# Generated by Django 2.2.17 on 2021-01-14 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20210113_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 0, 15, 51, 779697), verbose_name='Creado'),
        ),
    ]
