# Generated by Django 2.2.17 on 2021-01-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20210114_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True)),
                ('table_name', models.CharField(blank=True, max_length=132)),
                ('table_row', models.BigIntegerField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=16)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'task_change_logs',
            },
        ),
        migrations.AlterField(
            model_name='inveratask',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Creado'),
        ),
    ]
