# Generated by Django 2.2.17 on 2021-01-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20210115_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelChangeLogsModel',
        ),
    ]
