# Generated by Django 2.2.17 on 2021-01-15 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0013_delete_modelchangelogsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.CreateModel(
            name='TaskLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(auto_now_add=True)),
                ('title_task', models.CharField(blank=True, max_length=132)),
                ('action_log', models.CharField(choices=[('Creada', 'Creada'), ('Modificada', 'Modificada'), ('Eliminada', 'Eliminada')], max_length=50, verbose_name='Accion en tarea')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
