# Generated by Django 2.2.17 on 2021-01-16 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20210115_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklogs',
            name='title_task',
        ),
        migrations.AlterField(
            model_name='inveratask',
            name='userTask',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mi', to=settings.AUTH_USER_MODEL, verbose_name='El usuario se asigna automaticamente'),
        ),
        migrations.AlterField(
            model_name='tasklogs',
            name='action_log',
            field=models.CharField(max_length=50, verbose_name='Logs'),
        ),
        migrations.AlterField(
            model_name='tasklogs',
            name='user_id',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
