# Generated by Django 2.2.17 on 2021-01-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20210116_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inveratask',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tasklogs',
            name='action_log',
            field=models.CharField(max_length=200, verbose_name='Logs'),
        ),
    ]
